import { Router } from "express";
import * as externalActions from "../external-actions.js";
import * as artifacts from "../artifacts.js";
import { getPorkbunCredentials } from "../config.js";
import { purchaseDomain } from "../providers/porkbun.js";
import { emitSSE } from "./pipeline.js";

const router = Router();

// ---------------------------------------------------------------------------
// POST /api/external-actions/request
// Create a new pending action. Emits SSE external-action-requested.
// Body: { projectId, type, params }
// ---------------------------------------------------------------------------

router.post("/request", (req, res) => {
  const { projectId, type, params } = req.body;

  if (!projectId || !type) {
    return res.status(400).json({
      error: "Missing required fields",
      reason: "projectId and type are required",
    });
  }

  // ── Simulated data guard (D052) ──────────────────────────────────────
  if (type === "domain-purchase") {
    const domain = params?.domain;
    if (domain) {
      const projectArtifacts = artifacts.getByProject(projectId);
      const domainArtifact = projectArtifacts.find(
        (a) => a.type === "domain_signals",
      );
      if (
        domainArtifact?.metadata?.engine === "n8n-plan-domain-v1-simulated"
      ) {
        console.log(
          `[external-actions] request rejected: simulated data guard projectId=${projectId} domain=${domain}`,
        );
        return res.status(400).json({
          error: "Simulated data rejected",
          reason:
            "Domain signals were generated by a simulated engine (n8n-plan-domain-v1-simulated). Real domain data is required before purchasing.",
        });
      }
    }
  }

  try {
    const action = externalActions.requestAction({ projectId, type, params });
    emitSSE(projectId, "external-action-requested", {
      actionId: action.id,
      type: action.type,
      params: action.params,
      status: action.status,
      requestedAt: action.requestedAt,
    }, req.lumonUser?.login ?? null);
    console.log(
      `[external-actions] POST /request projectId=${projectId} actionId=${action.id}`,
    );
    res.status(201).json(action);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// ---------------------------------------------------------------------------
// POST /api/external-actions/confirm/:actionId
// Confirm a pending action. Emits SSE external-action-confirmed.
// Body: { projectId }
// ---------------------------------------------------------------------------

router.post("/confirm/:actionId", (req, res) => {
  const { actionId } = req.params;
  const { projectId } = req.body;

  if (!projectId) {
    return res.status(400).json({
      error: "Missing required field",
      reason: "projectId is required",
    });
  }

  try {
    const action = externalActions.confirmAction({ projectId, actionId });
    emitSSE(projectId, "external-action-confirmed", {
      actionId: action.id,
      status: action.status,
      confirmedAt: action.confirmedAt,
    }, req.lumonUser?.login ?? null);
    console.log(
      `[external-actions] POST /confirm/${actionId} projectId=${projectId}`,
    );
    res.json(action);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// ---------------------------------------------------------------------------
// POST /api/external-actions/cancel/:actionId
// Cancel a pending or confirmed action. Emits SSE external-action-cancelled.
// Body: { projectId }
// ---------------------------------------------------------------------------

router.post("/cancel/:actionId", (req, res) => {
  const { actionId } = req.params;
  const { projectId } = req.body;

  if (!projectId) {
    return res.status(400).json({
      error: "Missing required field",
      reason: "projectId is required",
    });
  }

  try {
    const action = externalActions.cancelAction({ projectId, actionId });
    emitSSE(projectId, "external-action-cancelled", {
      actionId: action.id,
      status: action.status,
    }, req.lumonUser?.login ?? null);
    console.log(
      `[external-actions] POST /cancel/${actionId} projectId=${projectId}`,
    );
    res.json(action);
  } catch (err) {
    res.status(400).json({ error: err.message });
  }
});

// ---------------------------------------------------------------------------
// POST /api/external-actions/execute/:actionId
// Execute a confirmed action via its provider. Returns 403 if not confirmed.
// Body: { projectId }
// ---------------------------------------------------------------------------

router.post("/execute/:actionId", async (req, res) => {
  const { actionId } = req.params;
  const { projectId } = req.body;

  if (!projectId) {
    return res.status(400).json({
      error: "Missing required field",
      reason: "projectId is required",
    });
  }

  // Look up the action first to determine the provider
  const action = externalActions.getAction(actionId);
  if (!action) {
    return res.status(404).json({
      error: "Action not found",
      reason: `No action with id ${actionId}`,
    });
  }

  // Build the provider callback based on action type
  let provider;
  if (action.type === "domain-purchase") {
    const creds = getPorkbunCredentials();
    provider = async (params) => {
      return purchaseDomain({
        domain: params.domain,
        cost: params.cost,
        apiKey: creds.apiKey,
        apiSecret: creds.apiSecret,
      });
    };
  } else {
    provider = async () => {
      throw new Error(`Unknown action type: ${action.type}`);
    };
  }

  try {
    const updated = await externalActions.executeAction({
      projectId,
      actionId,
      provider,
    });

    if (updated.status === "completed") {
      emitSSE(projectId, "external-action-completed", {
        actionId: updated.id,
        status: updated.status,
        result: updated.result,
        completedAt: updated.completedAt,
      }, req.lumonUser?.login ?? null);
      console.log(
        `[external-actions] POST /execute/${actionId} projectId=${projectId} status=completed`,
      );
    } else if (updated.status === "failed") {
      emitSSE(projectId, "external-action-failed", {
        actionId: updated.id,
        status: updated.status,
        error: updated.error,
      }, req.lumonUser?.login ?? null);
      console.log(
        `[external-actions] POST /execute/${actionId} projectId=${projectId} status=failed`,
      );
    }

    res.json(updated);
  } catch (err) {
    if (err.code === "CONFIRMATION_REQUIRED") {
      console.log(
        `[external-actions] POST /execute/${actionId} GATE REJECTED — not confirmed`,
      );
      return res.status(403).json({
        error: "Execution rejected",
        reason: err.message,
      });
    }
    res.status(500).json({ error: err.message });
  }
});

// ---------------------------------------------------------------------------
// GET /api/external-actions/status/:projectId
// Returns all actions for a project.
// ---------------------------------------------------------------------------

router.get("/status/:projectId", (req, res) => {
  const { projectId } = req.params;
  const actions = externalActions.getActions(projectId);

  console.log(
    `[external-actions] GET /status/${projectId} count=${actions.length}`,
  );
  res.json({ projectId, actions });
});

// ---------------------------------------------------------------------------
// GET /api/external-actions/action/:actionId
// Returns a single action.
// ---------------------------------------------------------------------------

router.get("/action/:actionId", (req, res) => {
  const { actionId } = req.params;
  const action = externalActions.getAction(actionId);

  if (!action) {
    return res.status(404).json({
      error: "Action not found",
      reason: `No action with id ${actionId}`,
    });
  }

  console.log(
    `[external-actions] GET /action/${actionId} status=${action.status}`,
  );
  res.json(action);
});

export default router;
